apiVersion: v1
kind: Service
metadata:
  name: portfolio-rabbitmq-service
spec:
  selector:
    app: portfolio-rabbitmq-managment
  type: NodePort
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672

    - name: managment
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 31672
