apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portfolio-rabbitmq-managment
  name: portfolio-rabbitmq-managment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-rabbitmq-managment
  template:
    metadata:
      labels:
        app: portfolio-rabbitmq-managment
    spec:
      containers:
        - name: portfolio-rabbitmq-managment
          image: rabbitmq:3.12-management
          imagePullPolicy: IfNotPresent
          resources: {}
          envFrom:
            - configMapRef:
                name: portfolio-rabbitmq-managment-configmap
          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc

