apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app: portfolio-web
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      # nodePort: 30080 
